# Generated by Django 2.2.7 on 2019-11-17 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientsphone',
            old_name='author',
            new_name='clients',
        ),
    ]
