# Generated by Django 2.2.7 on 2019-12-05 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0006_auto_20191128_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('data_begin', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_end', models.DateTimeField()),
                ('status_task', models.CharField(choices=[('DO', 'DONE'), ('PL', 'PLANE'), ('CA', 'CANCEL'), ('MO', 'MOVE')], default='DO', max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Задача менеджеру',
                'verbose_name_plural': 'Задачи менеджеру',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pole', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('data_edit', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'Истории',
            },
        ),
    ]
