# Generated by Django 2.2.7 on 2019-12-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_history_task_manager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment_client',
            options={'verbose_name': 'Коментарий о клиенте', 'verbose_name_plural': 'Коментарии о клиентах'},
        ),
        migrations.AlterField(
            model_name='task_manager',
            name='status_task',
            field=models.CharField(choices=[('DO', 'Выполнено'), ('PL', 'Заполанирована'), ('CA', 'Отменено'), ('MO', 'Перенесено')], default='DO', max_length=10),
        ),
    ]
